name: Build and release

on:
  push:
    tags:
      - '*'


jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout the repo
        uses: actions/checkout@v2
      # Get tag
      - name: Get tag
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      # Build
      - name: Build
        env:
          KERNEL_VERSION: ${{ steps.vars.outputs.tag }}
        run: chmod +x "${GITHUB_WORKSPACE}/build.sh" && "${GITHUB_WORKSPACE}/build.sh ${KERNEL_VERSION}"
      # Add to release
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: linux-kernel-amlogic-*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
          body: "Kernel release ${{ github.ref }}"
