name: test

on:
  push:
    tags:
      - '*'


jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest
    steps:
      # Check out
      - uses: actions/checkout@v2
      # Build
      - name: Build
        run: chmod +x "${GITHUB_WORKSPACE}/test.sh" && "${GITHUB_WORKSPACE}/test.sh"
      # Add to release
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "${GITHUB_WORKSPACE}/linux-kernel-amlogic-*"
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
          body: "Kernel release ${{ github.ref }}"
